notifications:
  email:
    on_success: never

install:
  - sudo apt-get update && sudo apt-get install -y pandoc

script:
  - bash render.sh

after_script:
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/c4pr1c3/LinuxSysAdmin.git # 设置 github 地址
