notifications:
  email:
    on_success: never

before_install:
  - export TZ='Asia/Shanghai'
  - openssl aes-256-cbc -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d -pbkdf2 -k ${SSH_PSW} 
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add

install:
  - sudo apt-get update 
  - wget https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb && sudo dpkg -i pandoc-2.9.1.1-1-amd64.deb

before_script:
  - pandoc -v

script:
  - bash render.sh

after_script:
  - git checkout -b gh-pages
  - git add *.html
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" gh-pages
  - git push --force --quiet git@gitee.com:c4pr1c3/LinuxSysAdmin.git gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/c4pr1c3/LinuxSysAdmin.git # 设置 github 地址

addons:
  ssh_known_hosts:
    - gitee.com
